version: '3.1'
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    networks:
      - ms-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: order-service
    ports:
      - "27017:27017"

  order-service:
    build: .
    image: nikitamane/order-service
    container_name: order-service
    restart: always
    depends_on:
      - mongodb
    networks:
      - ms-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/order-service?authSource=admin
    ports:
      - "1000:9092"

networks:
  ms-network:
    external: true
