server:
  port: 9092
 
spring:
 
  data:
    mongodb:
      uri: mongodb://nikita-mongo-container:27017/order-service

      
eureka:
 instance:
   prefer-ip-address: true
   
 client:
   serviceUrl:
     defaultZone: http://eureka-service:8761/eureka
     
   fetch-registry: true
   register-with-eureka: true
   
   
   


  

 